### ISSUE TITLE
Unable to import SmashGG stream queue due to UI Lock logic

### ISSUE THREAD

**Issue by vlee489** [inkfarer/ipl-overlay-controls#102]
Due to [line 47 in highlightedMatchPicker.vue](https://github.com/inkfarer/ipl-overlay-controls/blob/9abcf21af2369c2b04739402a99a7824a47c257b/src/dashboard/nextMatch/components/highlightedMatchPicker.vue#L47) not checking if Smash.gg stream data is filled, you're unable to import matches from stream queue.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1593698/164973614-3092f4be-6aad-4ce9-8868-1cd8d051d5d6.png">

Possible fix
```ts
stageDataPresent: computed(() => (!isEmpty(store.tournamentData.stages) || !isEmpty(store.tournamentData.meta.sourceSpecificData.smashgg.streams)))
```

**Comment by inkfarer** [comment]
Fixed in 4.1.0
