### ISSUE TITLE
Importing an empty Smash.gg Stream queue show error to user

### ISSUE THREAD

**Issue by vlee489** [inkfarer/ipl-overlay-controls#103]
When the smash.gg stream queue is empty, the user is presented with an error for the `forEach()` function.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/1593698/164973691-aa300344-4107-4dc0-8251-c844e901dd8e.png">

**Comment by inkfarer** [comment]
Fixed in 4.1.0
