### ISSUE TITLE
Casters cannot be re-ordered in certain rare cases

### ISSUE THREAD

**Issue by inkfarer** [inkfarer/ipl-overlay-controls#119]
If a caster's ID is entirely numeric (Regardless of type), JavaScript will sort it to the front of an object [(source)](https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/), no matter the insertion order. This means if we have casters with short numeric IDs, attempting to change their order will appear to have no effect.

In the case of importing casters from Radia, the IDs that get assigned to the casters is numeric, but is too long and therefore gets treated as a string.

### What do?

As a workaround in current versions, if the bug occurs at any time, removing and re-adding all casters should fix it.

In future versions, a few paths could be taken:
- Ensure casters cannot be saved with numeric IDs (could be error-prone)
    - Perhaps rewrite the `generateId()` helper to
return something more akin to an uuidv4, which cannot be treated as an integer by JS objects in any case.
- Save casters in a different format, likely an array (means changing commonly used public API)

**Comment by vlee489** [comment]
On the Radia API we could expose the ObjectID for each commentator that would be present that's a [BSON ObjectID](https://www.mongodb.com/docs/manual/reference/bson-types/#std-label-objectid) data type that can be handled as a string.

**Comment by inkfarer** [comment]
worked around: https://github.com/inkfarer/ipl-overlay-controls/commit/3aaf3a819ded77ae5ebdef9e7c663d2fce192886
