### ISSUE TITLE
Requests being sent to Radia Production Stack when no guild ID is provided

### ISSUE THREAD

**Issue by vlee489** [inkfarer/ipl-overlay-controls#123]
When the user has not entered a GuildID in the IPL configuration, the controls still sends a request with no guildID specifed and will always get returned a 404 and error out.

Fix: Check if a guildID is provided before sending the request.

Sentry Error: https://vincent-lee.sentry.io/issues/4489735896/events/0c5e43403db4403f95233d1373c53dfe/

**Comment by inkfarer** [comment]
ok: https://github.com/inkfarer/ipl-overlay-controls/commit/68ab24c3c8ff8cb85a5bc8eec8413a59db826197
