### ISSUE TITLE
Set predictions via the Twitch API

### ISSUE THREAD

**Issue by inkfarer** [inkfarer/ipl-overlay-controls#16]
https://dev.twitch.tv/docs/api/reference#create-prediction

**Comment by vlee489** [comment]
https://radia.iplabs.work/docs

- [x] Schema to store prediction data
- [x] Extension GET predictions
- [x] Extension POST predictions
- [x] Extension PATCH predictions
- [x] UI Design
- [x] UI Implementation

UI should use popup when issues arise or
