### ISSUE TITLE
Smash.gg StreamQueue support for highlighted matches

### ISSUE THREAD

**Issue by vlee489** [inkfarer/ipl-overlay-controls#46]
Add support for Smash.gg [StreamQueue](https://developer.smash.gg/docs/examples/queries/stream-queue) for getting highlighted matches

- [x] Edit team importer to use smash.gg IDs
- [x] Import stream stations from smash.gg
- [x] import streamQueue from smash.gg

**Comment by vlee489** [comment]
```gql
query EventEntrants($slug: String!) {
  tournament(slug: $slug) {
    streamQueue {
      id
    sets{
      completedAt
      displayScore
      event{
        name
      }
      slots{
        seed {
          groupSeedNum
        }
        entrant{
          id
          name
          participants{
            prefix
            gamerTag
          }
        }
      }
    }
  }
  }
}


```

**Comment by vlee489** [comment]
Sample data https://gist.github.com/vlee489/ae30cc8d45a0ce2d440a9e2257ffa253

**Comment by inkfarer** [comment]
Done in 3.1.0
