### ISSUE TITLE
Set Radia-productions tournament data from data importer

### ISSUE THREAD

**Issue by inkfarer** [inkfarer/ipl-overlay-controls#52]

**Comment by vlee489** [comment]
[API Docs here](https://radia.iplabs.work/docs#operation/set_guild_info_organisation_guild__guild_id__post)

For Battlefy Tournaments you can use the info given by `https://api.battlefy.com/tournaments/` to form the link to the bracket by doing 

```ts
`https://battlefy.com/${json.organisation.name}/${json.slug}/${json._id}/info?infoTab=details`
```

for Smash.gg
```ts
`https://smash.gg/tournament/${slug}/details`
```
