### ISSUE TITLE
Jest Unit Testing 

### ISSUE THREAD

**Issue by vlee489** [inkfarer/ipl-overlay-controls#54]
Add [Jest](https://jestjs.io/) Unit Test support for running unit tests on functions and extensions

**Comment by inkfarer** [comment]
- [x] See, if testing dashboard panels and extensions is feasible:
  - Can you test replicant change handlers?
  - Can you test message listeners (`listenFor`)?
- [x] Run tests from GitHub Actions

**Comment by inkfarer** [comment]
Happy to be able to close this tonight
