### ISSUE TITLE
Allows setting of source when importing tournament from JSON

### ISSUE THREAD

**Issue by vlee489** [inkfarer/ipl-overlay-controls#62]
When team data is imported via manual JSON fine, allow the file to contain data on the source and the tournament ID so platform-specific features can still work.

**Comment by inkfarer** [comment]
Completed in 3.2.0 - Both formats for team data are now supported. [(Commit)](https://github.com/inkfarer/ipl-overlay-controls/commit/b6fd25265173c0bf579d2d0374d2574108db9f89)
